# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy Petclinic 

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Jarfile 
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     - name: Build and Run Tests
       run: mvn test --batch-mode -Dmaven.test.failure.ignore=true
     - name: Create executable Jarfile
       run: mvn -B package -Dmaven.test.skip=true --file pom.xml
     - name: Deploy to heroku 
       uses: akhileshns/heroku-deploy@v3.6.8
       with:
           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
           heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
           heroku_email: ${{secrets.HEROKU_EMAIL}}
           procfile: "web: java -Dserver.port=$PORT $JAVA_OPTS -javaagent:newrelic/newrelic.jar -jar target/spring-petclinic-2.4.0.BUILD-SNAPSHOT.jar"
